### ISSUE TITLE
Add hostname check to script 

### ISSUE THREAD

**Issue by tosin2013** [redhat-et/microshift#176] opened 2021-07-21 21:50 UTC
If the hostname of the device is not a full fqdn the cluster will fail on restart. There can be a check on the install.sh script that checks if the hostname is fully qualified.

**Comment by tosin2013** [comment] 2021-07-21 21:50
```
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:3;nat_PREROUTING_POLICIES_pre:108 family=10 entries=156 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:1;mangle_PREROUTING_POLICIES_pre:288 family=1 entries=432 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:1;filter_IN_policy_allow-host-ipv6_allow:413 family=1 entries=433 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:1;filter_IN_policy_allow-host-ipv6_allow:413 family=1 entries=434 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:1;filter_IN_policy_allow-host-ipv6_allow:413 family=1 entries=435 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=firewalld:1;filter_IN_policy_allow-host-ipv6_allow:413 family=1 entries=436 op=nft_register_rule pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:34 fedora audit[789]: NETFILTER_CFG table=?:0;?:0 family=0 entries=3 op=nft_register_gen pid=789 subj=kernel comm="firewalld"
Jul 21 17:32:35 fedora microshift[790]: time="2021-07-21T17:32:35-04:00" level=fatal msg="failed to get host IP: no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\""
Jul 21 17:32:35 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 21 17:32:35 fedora systemd[1]: microshift.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 17:32:35 fedora systemd[1]: microshift.service: Failed with result 'exit-code'.
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Scheduled restart job, restart counter is at 1.
Jul 21 17:32:36 fedora systemd[1]: Stopped Microshift.
Jul 21 17:32:36 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora systemd[1]: Started Microshift.
Jul 21 17:32:36 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora microshift[910]: time="2021-07-21T17:32:36-04:00" level=fatal msg="failed to get host IP: no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\""
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Failed with result 'exit-code'.
Jul 21 17:32:36 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Scheduled restart job, restart counter is at 2.
Jul 21 17:32:36 fedora systemd[1]: Stopped Microshift.
Jul 21 17:32:36 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora systemd[1]: Started Microshift.
Jul 21 17:32:36 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 21 17:32:36 fedora microshift[927]: time="2021-07-21T17:32:36-04:00" level=fatal msg="failed to get host IP: no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\""
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 17:32:36 fedora systemd[1]: microshift.service: Failed with result 'exit-code'.
Jul 21 17:32:36 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=microshift comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jul 21 17:32:37 fedora systemd[1]: microshift.service: Scheduled restart job, restart counter is at 3.
Jul 21 17:32:37 fedora systemd[1]: Stopped Microshift.

```

**Comment by oglok** [comment] 2021-07-28 10:24
I'm not able to reproduce this bug. 

I used a fedora Vagrant VM (with a wrong FQDN hostname) and restarting microshift works, and I've been able to apply new manifests, deploy applications, etc.

What would be the steps to reproduce the bug?

**Comment by copejon** [comment] 2021-08-10 19:56
@tosin2013 If the PR satisfies this issue, please close it.

**Closed** 2021-08-10 20:40 UTC
